### PR TITLE
OCaml 4.03 compatibility

### PR DESCRIPTION
**Pull request by Khady**
I am not sure about the fix. I followed the suggestion of the compiler. But the test is passing.

### CODE REVIEW

**Comment by whitequark** [comment]
This breaks it on 4.02. Please add cppo like in this commit: https://github.com/whitequark/ppx_deriving_yojson/commit/9417696295b7b0169f8282bdd10597d2f078d385

The files you need are `opam`, `pkg/build.ml`, `myocamlbuild.ml`, and this hack: https://github.com/whitequark/ppx_deriving_yojson/commit/9417696295b7b0169f8282bdd10597d2f078d385#diff-7fa1cddad622d88b43f3838f86e70552R3.

**Comment by whitequark** [comment]
And I would also appreciate if you ported this commit over as well: https://github.com/whitequark/ppx_deriving_yojson/commit/3922531c3c76093e9aa3a02a00db0d705f22b86e

**Comment by Khady** [comment]
Thanks for the quick review. I will have a look at your links.

**Comment by Khady** [comment]
PR updated. Here is the log of a travis build: https://travis-ci.org/Khady/ppx_getenv/builds/127526467

**Comment by whitequark** [comment]
Thanks!

**Comment by gasche** [comment]
Would it be possible to do a ppx_getenv release with this fix? opam-builder currently reports that no ppx_getenv version works under 4.03 and 4.04 -- there may also be 4.04-specific issue but the automated builder fails on this incompatibility.

**Comment by whitequark** [comment]
@gasche Wish granted https://github.com/ocaml/opam-repository/pull/7197

**Comment by gasche** [comment]
Thanks! I may update the metadata of previous versions to mark availability as `< 4.03`, and I will let you know here if the automated builder gives further 4.04-specific issues.

**Pull request merged**
